### ISSUE TITLE
Publish v0.2.8 to crates.io

### ISSUE THREAD

**Issue by mi-ael** [virtualritz/polyhedron-operators#21]
Currently, v0.2.7 is the latest version of this awesome library available on crates. But on GitHub there is already a v0.2.8 version available, which fixes some issues for the current version of Bevy.

Could you publish the v0.2.8 version to crates.io?

**Comment by virtualritz** [comment]
Yes, I will get to it eventually. There are some blockers that have to do with the `nsi` crate.

In the meantime you can use an overlay in your `Cargo.toml`:

```toml
[patch.crates.io]
polyhedron-ops = { git = "https://github.com/virtualritz/polyhedron-ops.git" }
```
